version: "3.4"

services:
    client:
        image: client
        container_name: client
        build: 
            context: ./client
            dockerfile: client.Dockerfile
        links: 
            - mongodb
        restart: on-failure
        ports:
            - "3000:3000"
        command: ["npm","start"]
    api:
        image: api
        container_name: api
        build: 
            context: ./api
            dockerfile: api.Dockerfile
        restart: on-failure
        ports:
            - "5000:5000"
        depends_on:
            - mongodb
        command: ["npm","start"]
    mongodb:
        image: mongo
        container_name: mongodb
        restart: always
        ports:
            - 27017:27017
   